# Generated by Django 5.2.4 on 2025-07-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home', 'Home'), ('toys', 'Toys')], max_length=64),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
