# Generated by Django 5.2.4 on 2025-07-26 04:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_user_watchlist_delete_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='offer',
            new_name='new_bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
